# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/ortools:latest
# For Pyomo, use the following runtime:
# runtime: ghcr.io/nextmv-io/runtime/pyomo:latest

# For AMPL, use the following runtime:
# runtime: ghcr.io/nextmv-io/runtime/ampl:latest

# For Gurobi, use the following runtime and add the licence file 'gurobi.lic' to the files list:
# runtime: ghcr.io/nextmv-io/runtime/gurobi:latest

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
